# Generated by Django 3.0.6 on 2020-09-29 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0004_auto_20200929_1731'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrederItem',
            new_name='OrderItem',
        ),
    ]
